const adminClient = window.supabase.createClient(window.SUPABASE_CONFIG.url, window.SUPABASE_CONFIG.publishableKey);
const state = { regions: [], people: [], resources: [], slides: [], runway: [], leads: [] };
const $ = (selector) => document.querySelector(selector);
const formValues = (form) => Object.fromEntries(new FormData(form).entries());
const toBool = (value) => value === true || value === "true";
const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;" }[char]));
function showDashboard(session) { const loggedIn = Boolean(session); $("#loginCard").classList.toggle("hidden", loggedIn); $("#dashboard").classList.toggle("hidden", !loggedIn); $("#signOut").classList.toggle("hidden", !loggedIn); if (loggedIn) loadAll(); }
async function getRows(table, order = "sort_order") { const result = await adminClient.from(table).select("*").order(order, { ascending: true }); if (result.error) throw result.error; return result.data || []; }
async function loadAll() { try { state.regions = await getRows("regions"); state.people = await getRows("people"); state.resources = await getRows("resources"); state.slides = await getRows("carousel_slides"); state.runway = await getRows("runway_photos"); const leadResult = await adminClient.from("leads").select("*").order("created_at", { ascending: false }); if (leadResult.error) throw leadResult.error; state.leads = leadResult.data || []; renderAll(); const setting = await adminClient.from("site_settings").select("*").eq("id", 1).single(); if (setting.data) Object.entries(setting.data).forEach(([key, value]) => { const field = $(`[name="${key}"]`); if (field) field.value = value ?? ""; }); } catch (error) { console.error("Admin data loading failed:", error); $("#leadsStatus").textContent = `加载失败：${error.message}`; } }
function renderAll() { $("#peopleList").innerHTML = state.people.map((item) => row(item, "people", item.image_url, `${item.name} · ${item.role}`)).join(""); $("#regionsList").innerHTML = state.regions.map((item) => row(item, "regions", "", `${item.name} · ${item.english_name}`)).join(""); $("#resourcesList").innerHTML = state.resources.map((item) => row(item, "resources", item.image_url, `${item.name} · ${state.regions.find((r) => r.id === item.region_id)?.name || ""}`)).join(""); $("#slidesList").innerHTML = state.slides.map((item) => row(item, "carousel_slides", item.image_url, item.title)).join(""); $("#runwayList").innerHTML = state.runway.map((item) => row(item, "runway_photos", item.image_url, `${item.lane} · ${item.label}`)).join(""); $("#leadsList").innerHTML = state.leads.length ? state.leads.map((item) => `<div class="data-row"><span>${escapeHtml(item.name)}<br>${escapeHtml(item.email)}</span><span>${escapeHtml(item.phone)}</span><span>${escapeHtml(item.city)}<br>${escapeHtml(item.topic)}</span><span>${new Date(item.created_at).toLocaleString()}<br>${escapeHtml(item.message)}</span></div>`).join("") : "<p class=\"muted\">暂无提交资料。</p>"; $("#resourceRegion").innerHTML = state.regions.map((r) => `<option value="${r.id}">${escapeHtml(r.name)}</option>`).join(""); }
function row(item, table, image, label) { return `<div class="data-row">${image ? `<img src="${escapeHtml(image)}" alt="">` : `<span>${escapeHtml(label)}</span>`}<span>${image ? escapeHtml(label) : escapeHtml(item.description || "")}</span><span>${item.is_visible === false ? "隐藏" : "显示"}</span><span class="row-actions"><button class="small-button" data-edit="${table}" data-id="${item.id}">编辑</button><button class="small-button danger" data-delete="${table}" data-id="${item.id}">删除</button></span></div>`; }
async function save(table, form, statusId) { const values = formValues(form); const id = values.id; delete values.id; if ("sort_order" in values) values.sort_order = Number(values.sort_order || 0); if ("is_visible" in values) values.is_visible = toBool(values.is_visible); const result = id ? await adminClient.from(table).update(values).eq("id", id) : await adminClient.from(table).insert(values); if (result.error) throw result.error; $(`#${statusId}`).textContent = "已保存"; form.reset(); await loadAll(); }
function bindCrud(formId, table, statusId) { $(`#${formId}`).addEventListener("submit", async (event) => { event.preventDefault(); try { await save(table, event.currentTarget, statusId); } catch (error) { console.error("Admin save failed:", error); $(`#${statusId}`).textContent = `保存失败：${error.message}`; } }); }
document.addEventListener("click", async (event) => { const edit = event.target.closest("[data-edit]"); const remove = event.target.closest("[data-delete]"); if (event.target.matches("[data-reset]")) { $( `#${event.target.dataset.reset}`).reset(); return; } if (edit) { const item = state[edit.dataset.edit === "carousel_slides" ? "slides" : edit.dataset.edit === "runway_photos" ? "runway" : edit.dataset.edit][(state[edit.dataset.edit === "carousel_slides" ? "slides" : edit.dataset.edit === "runway_photos" ? "runway" : edit.dataset.edit].findIndex((rowItem) => String(rowItem.id) === edit.dataset.id))]; const form = edit.dataset.edit === "people" ? $("#personForm") : edit.dataset.edit === "regions" ? $("#regionForm") : edit.dataset.edit === "resources" ? $("#resourceForm") : edit.dataset.edit === "carousel_slides" ? $("#slideForm") : $("#runwayForm"); Object.entries(item).forEach(([key, value]) => { if (form.elements[key]) form.elements[key].value = value ?? ""; }); return; } if (remove && confirm("确定删除这条内容吗？")) { const result = await adminClient.from(remove.dataset.delete).delete().eq("id", remove.dataset.id); if (result.error) alert(`删除失败：${result.error.message}`); else loadAll(); } });
$("#loginForm").addEventListener("submit", async (event) => { event.preventDefault(); const result = await adminClient.auth.signInWithPassword(formValues(event.currentTarget)); $("#loginStatus").textContent = result.error ? `登录失败：${result.error.message}` : ""; });
$("#settingsForm").addEventListener("submit", async (event) => { event.preventDefault(); const result = await adminClient.from("site_settings").upsert({ id: 1, ...formValues(event.currentTarget), updated_at: new Date().toISOString() }); $("#settingsStatus").textContent = result.error ? `保存失败：${result.error.message}` : "已保存"; });
bindCrud("personForm", "people", "personStatus"); bindCrud("regionForm", "regions", "regionStatus"); bindCrud("resourceForm", "resources", "resourceStatus"); bindCrud("slideForm", "carousel_slides", "slideStatus"); bindCrud("runwayForm", "runway_photos", "slideStatus");
document.querySelectorAll(".tab").forEach((tab) => tab.addEventListener("click", () => { document.querySelectorAll(".tab").forEach((item) => item.classList.toggle("active", item === tab)); document.querySelectorAll(".panel").forEach((panel) => panel.classList.toggle("hidden", panel.dataset.panel !== tab.dataset.tab)); }));
$("#exportLeads").addEventListener("click", () => { const csv = ["姓名,邮箱,电话,城市,需求,说明,时间", ...state.leads.map((item) => [item.name,item.email,item.phone,item.city,item.topic,item.message,item.created_at].map((value) => `"${String(value ?? "").replaceAll('"','""')}"`).join(","))].join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob(["\ufeff" + csv], { type: "text/csv" })); link.download = "leads.csv"; link.click(); URL.revokeObjectURL(link.href); });
$("#signOut").addEventListener("click", () => adminClient.auth.signOut()); adminClient.auth.onAuthStateChange((_event, session) => showDashboard(session)); adminClient.auth.getSession().then(({ data }) => showDashboard(data.session));
