create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  language text not null default 'zh' check (language in ('zh', 'en')),
  company_name text not null default 'GLOBAL PEOPLE',
  hero_title text not null default '连接全球优质人才与机会',
  hero_intro text not null default '从人才、资源到区域市场，建立一条清晰、可靠的全球连接路径。',
  company_intro text not null default '此处填写品牌故事、服务能力、办公地点或视频介绍。',
  section_one_title text not null default '连接全球优质人才与机会',
  section_one_title_en text not null default 'Connect global talent and opportunity',
  section_one_intro text not null default '从人才、资源到区域市场，建立一条清晰、可靠的全球连接路径。',
  section_one_intro_en text not null default 'Build a clear and reliable path connecting talent, resources, and regional markets.',
  section_two_title text not null default '认识我们的人才网络',
  section_two_title_en text not null default 'Meet our talent network',
  section_two_intro text not null default '几十位专业人才的简介展示位。公司可以在后台替换姓名、职位、介绍和头像。',
  section_two_intro_en text not null default 'A showcase for professional talent profiles. Replace names, roles, introductions, and images from the admin panel.',
  section_three_title text not null default '在世界各地发现可能',
  section_three_title_en text not null default 'Discover possibilities worldwide',
  section_three_intro text not null default '选择区域，进入对应的人才与资源内容。',
  section_three_intro_en text not null default 'Choose a region to explore its people and resource content.',
  customer_service_url text not null default 'https://example.com/customer-service',
  updated_at timestamptz not null default now()
);
create table if not exists public.regions (
  id bigint generated by default as identity primary key,
  name text not null, english_name text not null default '', description text not null default '',
  sort_order integer not null default 0, is_visible boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.people (
  id bigint generated by default as identity primary key,
  name text not null, role text not null default '', description text not null default '',
  image_url text, sort_order integer not null default 0, is_visible boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  region_id bigint not null references public.regions(id) on delete cascade,
  name text not null, description text not null default '', image_url text,
  sort_order integer not null default 0, is_visible boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.carousel_slides (
  id bigint generated by default as identity primary key,
  title text not null default '', image_url text, link_url text,
  sort_order integer not null default 0, is_visible boolean not null default true
);
create table if not exists public.runway_photos (
  id bigint generated by default as identity primary key,
  image_url text, label text not null default '', lane text not null default 'left',
  sort_order integer not null default 0, is_visible boolean not null default true
);
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null, email text not null, phone text, city text, topic text, message text,
  created_at timestamptz not null default now()
);

insert into public.site_settings (id) values (1) on conflict (id) do nothing;
insert into public.regions (name, english_name, description, sort_order)
select * from (values
  ('北美','NORTH AMERICA','连接成熟市场与专业人才',1),
  ('拉丁美洲','LATIN AMERICA','发现充满活力的区域机会',2),
  ('欧洲','EUROPE','探索多元文化与创新资源',3),
  ('亚洲','ASIA','链接高速发展的核心市场',4),
  ('东南亚','SOUTHEAST ASIA','进入增长中的新兴区域',5),
  ('更多区域','MORE REGIONS','验收后可扩展新的分类',6)
) as seed(name, english_name, description, sort_order)
where not exists (select 1 from public.regions);

alter table public.site_settings enable row level security;
alter table public.regions enable row level security;
alter table public.people enable row level security;
alter table public.resources enable row level security;
alter table public.carousel_slides enable row level security;
alter table public.runway_photos enable row level security;
alter table public.leads enable row level security;

drop policy if exists "public read site settings" on public.site_settings;
drop policy if exists "public read regions" on public.regions;
drop policy if exists "public read people" on public.people;
drop policy if exists "public read resources" on public.resources;
drop policy if exists "public read slides" on public.carousel_slides;
drop policy if exists "public read runway photos" on public.runway_photos;
drop policy if exists "public submit leads" on public.leads;
drop policy if exists "admins manage site settings" on public.site_settings;
drop policy if exists "admins manage regions" on public.regions;
drop policy if exists "admins manage people" on public.people;
drop policy if exists "admins manage resources" on public.resources;
drop policy if exists "admins manage slides" on public.carousel_slides;
drop policy if exists "admins manage runway photos" on public.runway_photos;
drop policy if exists "admins read leads" on public.leads;

create policy "public read site settings" on public.site_settings for select to anon, authenticated using (true);
create policy "public read regions" on public.regions for select to anon, authenticated using (is_visible = true);
create policy "public read people" on public.people for select to anon, authenticated using (is_visible = true);
create policy "public read resources" on public.resources for select to anon, authenticated using (is_visible = true);
create policy "public read slides" on public.carousel_slides for select to anon, authenticated using (is_visible = true);
create policy "public read runway photos" on public.runway_photos for select to anon, authenticated using (is_visible = true);
create policy "public submit leads" on public.leads for insert to anon, authenticated with check (true);
create policy "admins manage site settings" on public.site_settings for all to authenticated using (true) with check (true);
create policy "admins manage regions" on public.regions for all to authenticated using (true) with check (true);
create policy "admins manage people" on public.people for all to authenticated using (true) with check (true);
create policy "admins manage resources" on public.resources for all to authenticated using (true) with check (true);
create policy "admins manage slides" on public.carousel_slides for all to authenticated using (true) with check (true);
create policy "admins manage runway photos" on public.runway_photos for all to authenticated using (true) with check (true);
create policy "admins read leads" on public.leads for select, update, delete to authenticated using (true) with check (true);

insert into storage.buckets (id, name, public) values ('site-media','site-media',true) on conflict (id) do update set public = true;
drop policy if exists "public read site media" on storage.objects;
drop policy if exists "admins upload site media" on storage.objects;
drop policy if exists "admins delete site media" on storage.objects;
create policy "public read site media" on storage.objects for select using (bucket_id = 'site-media');
create policy "admins upload site media" on storage.objects for insert to authenticated with check (bucket_id = 'site-media');
create policy "admins delete site media" on storage.objects for delete to authenticated using (bucket_id = 'site-media');
