create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  city text,
  topic text,
  message text,
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  customer_service_url text not null default 'https://example.com/customer-service',
  updated_at timestamptz not null default now()
);

alter table public.leads enable row level security;
alter table public.site_settings enable row level security;

create policy "public can submit leads" on public.leads
  for insert to anon, authenticated with check (true);
create policy "authenticated admins can read leads" on public.leads
  for select to authenticated using (true);
create policy "public can read customer service setting" on public.site_settings
  for select to anon, authenticated using (true);
create policy "authenticated admins can update customer service setting" on public.site_settings
  for all to authenticated using (true) with check (true);

insert into public.site_settings (id) values (1)
on conflict (id) do nothing;
