const fallbackServiceUrl = "https://example.com/customer-service";
window.supabaseClient = window.supabase && window.SUPABASE_CONFIG ? window.supabase.createClient(window.SUPABASE_CONFIG.url, window.SUPABASE_CONFIG.publishableKey) : null;
const regions = [{ name: "北美", en: "NORTH AMERICA", description: "连接成熟市场与专业人才" }, { name: "拉丁美洲", en: "LATIN AMERICA", description: "发现充满活力的区域机会" }, { name: "欧洲", en: "EUROPE", description: "探索多元文化与创新资源" }, { name: "亚洲", en: "ASIA", description: "链接高速发展的核心市场" }, { name: "东南亚", en: "SOUTHEAST ASIA", description: "进入增长中的新兴区域" }, { name: "更多区域", en: "MORE REGIONS", description: "验收后可扩展新的分类" }];
let currentRegion = 0; let serviceUrl = fallbackServiceUrl;
const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char]));
const placeholderImage = (label) => `<span>MEDIA PLACEHOLDER<br />${escapeHtml(label)}</span>`;
function mediaCard(item, index, fallbackLabel) { const isVideo = item?.link_url && /\.(mp4|webm|mov)(\?|$)/i.test(item.link_url); const source = item?.image_url || item?.link_url; const visual = source ? (isVideo ? `<video src="${escapeHtml(source)}" muted autoplay loop playsinline></video>` : `<img src="${escapeHtml(source)}" alt="${escapeHtml(item.title || item.label || fallbackLabel)}">`) : placeholderImage(`${fallbackLabel} ${String(index + 1).padStart(2, "0")}`); return `<article class="media-card">${visual}<span class="media-badge">${isVideo ? "VIDEO" : "IMAGE"}</span><strong>${escapeHtml(item?.title || item?.label || fallbackLabel)}</strong></article>`; }
function renderMedia(target, items, label) { const list = items.length ? items : Array.from({ length: 5 }, (_, index) => ({ title: label })); $(target).innerHTML = list.concat(list).map((item, index) => mediaCard(item, index, label)).join(""); }
function renderRegions() { $("#regionOptions").innerHTML = regions.map((region, index) => `<button class="region-card ${index === currentRegion ? "active" : ""}" data-region="${index}" type="button"><span class="number">0${index + 1}</span><strong>${escapeHtml(region.name)}</strong><small>${escapeHtml(region.en)}</small><span>↗</span></button>`).join(""); document.querySelectorAll(".region-card").forEach((card) => card.addEventListener("click", () => { currentRegion = Number(card.dataset.region); renderRegions(); })); }
const modal = $("#formModal"); function openForm() { modal.hidden = false; document.body.style.overflow = "hidden"; setTimeout(() => modal.querySelector("input")?.focus(), 0); } function closeForm() { modal.hidden = true; document.body.style.overflow = ""; }
document.addEventListener("click", (event) => { if (event.target.closest(".open-form")) openForm(); }); $("#closeModal").addEventListener("click", closeForm); modal.addEventListener("click", (event) => { if (event.target === modal) closeForm(); }); document.addEventListener("keydown", (event) => { if (event.key === "Escape" && !modal.hidden) closeForm(); });
$("#leadForm").addEventListener("submit", async (event) => { event.preventDefault(); const status = $("#formStatus"); status.textContent = "正在提交..."; if (!window.supabaseClient) { status.textContent = "当前为演示模式，请稍后再试。"; return; } const { error } = await window.supabaseClient.from("leads").insert(Object.fromEntries(new FormData(event.target).entries())); if (error) { console.error("Lead submission failed:", error); status.textContent = "提交失败，请稍后重试或直接联系客服。"; return; } status.textContent = "提交成功，我们会尽快与您联系。"; event.target.reset(); });
$("#supportFab").addEventListener("click", () => window.open(serviceUrl, "_blank", "noopener,noreferrer"));
renderRegions(); renderMedia("#topMedia", [], "首页媒体"); renderMedia("#peopleMedia", [], "人才媒体"); renderMedia("#regionMedia", [], "区域媒体");
async function loadPublishedContent() { if (!window.supabaseClient) return; try { const [settingsResult, peopleResult, regionsResult, slidesResult, runwayResult, resourcesResult] = await Promise.all([window.supabaseClient.from("site_settings").select("*").eq("id", 1).maybeSingle(), window.supabaseClient.from("people").select("*").eq("is_visible", true).order("sort_order"), window.supabaseClient.from("regions").select("*").eq("is_visible", true).order("sort_order"), window.supabaseClient.from("carousel_slides").select("*").eq("is_visible", true).order("sort_order"), window.supabaseClient.from("runway_photos").select("*").eq("is_visible", true).order("sort_order"), window.supabaseClient.from("resources").select("*").eq("is_visible", true).order("sort_order")]); if (settingsResult.error) throw settingsResult.error; const settings = settingsResult.data; if (settings) { $("#sectionOneTitle").innerHTML = escapeHtml(settings.section_one_title || settings.hero_title || "连接全球\n优质人才与机会").replace("\n", "<br>"); $("#sectionOneIntro").textContent = settings.section_one_intro || settings.hero_intro || ""; $("#sectionTwoTitle").innerHTML = escapeHtml(settings.section_two_title || "认识我们的\n人才网络").replace("\n", "<br>"); $("#sectionTwoIntro").textContent = settings.section_two_intro || settings.company_intro || ""; $("#sectionThreeTitle").innerHTML = escapeHtml(settings.section_three_title || "在世界各地\n发现可能").replace("\n", "<br>"); $("#sectionThreeIntro").textContent = settings.section_three_intro || "选择区域，进入对应的人才与资源内容。"; serviceUrl = settings.customer_service_url || fallbackServiceUrl; } if (peopleResult.data?.length) renderMedia("#peopleMedia", peopleResult.data, "人才"); if (slidesResult.data?.length) renderMedia("#topMedia", slidesResult.data, "首页"); const regionMedia = runwayResult.data?.length ? runwayResult.data : resourcesResult.data || []; if (regionMedia.length) renderMedia("#regionMedia", regionMedia, "区域"); if (regionsResult.data?.length) { regions.splice(0, regions.length, ...regionsResult.data.map((region) => ({ ...region, en: region.english_name }))); renderRegions(); } } catch (error) { console.error("Published content loading failed:", error); } }
loadPublishedContent();
